name: Azure Static Web Apps CI/CD


on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          # Runs a set of commands using the runners shell
      - name: Create google service account key file
        run: echo '${{ secrets.GOOGLE_SERVICEACCOUNT_KEY_FILE_CONTENT }}' >  BE-survey-manager/src/main/resources/${{ secrets.GOOGLE_SERVICEACCOUNT_KEY_FILE_NAME }}.json

      - name: ls
        run: ls -a

      - name: Run docker-compose
        run: docker-compose up -d --build

      - name: Sleep for 60 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '60s'

      - name: Check running containers
        run: docker ps

      - name: Copy static generated web pages
        run: docker cp jiu-jitsu-surveys_frontend_1:/usr/src/out ./

      - name: Run ls
        run: ls -a

      - name: Deploy
        id: deploy
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_NICE_OCEAN_087B84903 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match you app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "api" # Api source code path - optional
          output_location: "out" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_NICE_OCEAN_087B84903 }}
          action: "close"
